### ISSUE TITLE
Properties should be first definition

### ISSUE THREAD

**Issue by lebedyncrs** [DarkUkrainian/todo_list#2]
https://github.com/DarkUkrainian/todo_list/blob/0301e84736da82b189e6ed91921139821d84f72c/app/Models/Models/Task.php#L20

Move table property to the beginning of the class.

There is a standard about right order of class body:
1. Constants
2. Fields by visibility (public, protected, private)
3. Constructor and destructor and other magic methods
4. Methods by visibility (public, protected, private)

**Comment by OverSoon** [comment]
Take it.
find https://www.php.net/manual/ru/language.oop5.php
